### PR TITLE
Make tests independent of platform specific path separator (#219)

### LINKED ISSUE #219: Tests fail on Windows
### Description
Several tests fail on Windows due to the way slashes are being handled. For example in `test/rev.js`
```javascript
test('handles a `.` in the folder name', async t => {
	const stream = rev();
	const data = pEvent(stream, 'data');

	stream.end(createFile({
		path: 'mysite.io/unicorn.css'
	}));

	const file = await data;
	t.is(file.path, 'mysite.io/unicorn-d41d8cd98f.css');
	t.is(file.revOrigPath, 'mysite.io/unicorn.css');
});
```
On Windows the value of the `file.path` variable will be `mysite.io\\unicorn-d41d8cd98f.css` (due to the `path.join()` that is used internally by the **`modify-file`** module). This can be resolved by instead comparing to `path.normalize('mysite.io/unicorn-d41d8cd98f.css'))`.
Note that the `file.revOrigPath` comparison here should be left as is, since that value doesn't get transformed by any of `path`'s methods.

Similarly in `test/manifest.js` for example the
```javascript
MANIFEST[path.join('foo', 'scriptfoo.js')] = path.join('foo', 'scriptfoo-d41d8cd98f.js');
```
rules will also cause problems because the **`gulp-rev`** code will use `.replace(/\\/g, '/')` to "normalize" the paths before writing them to the manifest file. Here appending a `.replace(/\\/g, '/')` at the proper locations would solve those issues.
```javascript
MANIFEST[path.join('foo', 'scriptfoo.js').replace(/\\/g, '/')] = path.join('foo', 'scriptfoo-d41d8cd98f.js').replace(/\\/g, '/');
```

#### Steps to reproduce
Run `npm test` on Windows.

### PR DESCRIPTION
**Pull request by WVmf**
Resolves #219

Most of the path module's method will replace forward and backward
slashes with the platform specific path separator. And gulp-rev enforces
the use of forward slashes for the manifest. The tests didn't take these
two behaviors into account, which resulted in mismatches for some test
on platforms that use backward slashes as the path separator (i.e. the
Windows platform).

These mismatches are resolved by this patch by using `path.normalize()`
and `.replace(/\\/g, '/')` at the proper places in the tests.

### CODE REVIEW

**Comment by WVmf** [comment]
Hi @Zhouzi,

These changes are indeed limited to the test files and don't change anything in the [index.js](https://github.com/sindresorhus/gulp-rev/blob/master/index.js)
I encountered the problems with the test files while trying to create a fix for issue #220. For which I'll create another pull request after I get some feedback on that issue regarding the possible valid values for a `vinyl` file's `cwd`, `base` and `path` properties.

File: test/manifest.js [hunk 1]
```diff
@@ -174,19 +174,19 @@ test('uses correct base path for each file', async t => {
 	stream.write(createFile({
 		cwd: 'app/',
 		base: 'app/',
-		path: path.join('app', 'foo', 'scriptfoo-d41d8cd98f.js'),
+		path: path.join('app', 'foo', 'scriptfoo-d41d8cd98f.js').replace(/\\/g, '/'),
```
Comment (sindresorhus) [inline test/manifest.js]: This shouldn't be necessary as the path should be normalized in the code. If it is, it's probably a bug somewhere in the code.

File: test/manifest.js [hunk 2]
```diff
@@ -126,8 +126,8 @@ test('respects directories', async t => {
 	}));
 
 	const MANIFEST = {};
-	MANIFEST[path.join('foo', 'unicorn.css')] = path.join('foo', 'unicorn-d41d8cd98f.css');
-	MANIFEST[path.join('bar', 'pony.css')] = path.join('bar', 'pony-d41d8cd98f.css');
+	MANIFEST[path.join('foo', 'unicorn.css').replace(/\\/g, '/')] = path.join('foo', 'unicorn-d41d8cd98f.css').replace(/\\/g, '/');
+	MANIFEST[path.join('bar', 'pony.css').replace(/\\/g, '/')] = path.join('bar', 'pony-d41d8cd98f.css').replace(/\\/g, '/');
```
Comment (sindresorhus) [inline test/manifest.js]: I don't really know why we're using `path.join` here. We can just remove the joining and specify the paths directly. E.g. `'foo/unicorn.css'`.

File: test/manifest.js (hunk 1 above)
Comment (WVmf) [inline test/manifest.js]: This indeed seems to be due to a bug in the `relPath()` function. (Which is also related to #220.) With the following modification to `relPath()` the two `.replace(/\\/g, '/')` calls in this particular test aren't needed anymore:
```diff
function relPath(base, filePath) {
+	filePath = filePath.replace(/\\/g, '/');
+	base = base.replace(/\\/g, '/');

	if (filePath.indexOf(base) !== 0) {
-		return filePath.replace(/\\/g, '/');
+		return filePath;
	}

-	const newPath = filePath.slice(base.length).replace(/\\/g, '/');
+	const newPath = filePath.slice(base.length);

	if (newPath[0] === '/') {
		return newPath.slice(1);
	}

	return newPath;
}
```
I.e. in the original code the first if-test would always resolve to `true` on Windows because `file.path` was platform dependent due to `path.join()` while `file.base` was the platform independent `app/`. Which in turn resulted in the (normalized) full `file.path` to be returned instead of the relative path.

**Comment by sindresorhus** [comment]
@Zhouzi LGTY now?

**Comment by Zhouzi** [comment]
@sindresorhus just merged, might need a new release.

**Comment by sindresorhus** [comment]
Is it a breaking change?

**Comment by Zhouzi** [comment]
Nope 👌

**Comment by sindresorhus** [comment]
Actually, it is a major release because of https://github.com/sindresorhus/gulp-rev/commit/8686e62b380a22976f314687bd3f79ca69cae24f.

**Comment by WVmf** [comment]
Hi,
Thank you for merging the changes. Regarding the new release, maybe postpone it a little more because I was planning another pull request for #220.

**Comment by WVmf** [comment]
Ok just saw the new release was already made, so disregard the postponing part of my previous comment :)
